version: '3.7'
services:
  server-discovery-services:
    image: wortiz1027/server-discovery:latest
    container_name: server-discovery
    hostname: server-discovery
    restart: always
    ports:
      - 7071:7071
      - 6171:6171
    environment:
      - SERVER_CONFIG=http://server-config:7070
    networks:
      - ntw_backend
networks:
  ntw_backend:
    external: true